/**
 * Upgrade-Path Regression Test
 *
 * Usage: node tests/run-electron-node-test.cjs tests/upgrade-path.test.ts
 *
 * Fresh-install tests (schema-health.test.ts) only ever see a customers
 * table built by *today's* createSchema() — which already includes every
 * column createSchema() has ever grown, since it's a single function
 * describing the current desired shape. They can never catch the class of
 * bug fixed in 9c92409: a column (customers.country_code, then
 * customers.tag_counts) was added straight into createSchema() without a
 * paired ALTER migration for pre-existing installs, so any real install
 * whose customers table was created before those columns existed kept
 * missing them forever — CREATE TABLE IF NOT EXISTS in migration v1 is a
 * no-op once the table already exists. It crashed with
 * "no such column: country_code" the first time migration v23 tried to
 * use it (reported on a v1.9.7 upgrade).
 *
 * This test runs the *real* migration chain against a real database
 * fixture captured from an actual old release (tests/fixtures/upgrade-
 * snapshots/pre-migration-scheme-v1.5.0.db, generated by
 * scripts/generate-upgrade-fixture.ts / see specs/DatabaseMigrations.md) —
 * the only way to reproduce "an install whose table predates a column that
 * now only lives in createSchema()". If a future column gets added to
 * createSchema() without a matching guarded migration, this test fails the
 * same way production did, instead of a user finding out on upgrade.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-upgrade-path-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/pre-migration-scheme-v1.5.0.db');
const upgradeDbPath = path.join(testDir, 'flo.db');
fs.copyFileSync(FIXTURE, upgradeDbPath);

const FixtureDatabase = require('better-sqlite3');
const fixtureDb = new FixtureDatabase(upgradeDbPath);
const legacyTaxBreakdown = JSON.stringify([{ title: 'Legacy Tax', rate: 5, amount: 5 }]);
const legacyOrder = fixtureDb.prepare(`
  INSERT INTO orders (order_number, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('ORD-LEGACY-TAX', 100, 5, ?, 105)
`).run(legacyTaxBreakdown);
const legacyBill = fixtureDb.prepare(`
  INSERT INTO bills (bill_number, order_id, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('INV-LEGACY-TAX', ?, 100, 5, ?, 105)
`).run(legacyOrder.lastInsertRowid, legacyTaxBreakdown);
fixtureDb.prepare(`UPDATE bills SET payment_details = ? WHERE id = ?`).run(
  JSON.stringify({ method: 'upi', amount: 105, timestamp: '2026-07-01T11:30:00.000Z' }),
  legacyBill.lastInsertRowid,
);
fixtureDb.prepare(`
  INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES
    ('cloud_sync_enabled', '0', '2026-08-01 12:00:00'),
    ('cloud_pending_store_id', 'old-pending-id', '2026-08-01 12:00:00'),
    ('cloud_server_url', 'https://example.test/', '2026-08-01 12:00:00')
`).run();
fixtureDb.prepare(`
  INSERT OR REPLACE INTO settings (key, value, updated_at)
  VALUES ('cloud_orders_enabled', '0', '2026-08-01T12:00:00.000Z')
`).run();
// Pre-v45 era rows written by the old `now()` (ISO-8601 with T/Z/ms). Migration
// v45 must normalize these to the space form so range/order/compare operations
// see one consistent format.
const isoOrder = fixtureDb.prepare(`
  INSERT INTO orders (order_number, subtotal, tax_amount, total, created_at, updated_at, cooking_started_at, ready_at)
  VALUES ('ORD-ISO-TS', 10, 0, 10, '2026-07-01T10:00:00.123Z', '2026-07-01T10:00:00.123Z', '2026-07-01T10:05:00.000Z', '2026-07-01T10:12:00.000Z')
`).run();
fixtureDb.prepare(`
  INSERT INTO bills (bill_number, order_id, subtotal, tax_amount, total, paid_at, created_at, updated_at)
  VALUES ('INV-ISO-TS', ?, 10, 0, 10, '2026-07-01T11:30:00.000Z', '2026-07-01T11:00:00.000Z', '2026-07-01T11:30:00.000Z')
`).run(isoOrder.lastInsertRowid);
fixtureDb.close();

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};

Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function main() {
  console.log('🧪 FloDesktop Upgrade-Path Regression Test');
  console.log('='.repeat(60));

  const {
    initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb,
  } = require('../main/db');
  const { runHealthCheck } = require('../main/services/schema-health');

  // ── The real chain, against a real old install, must not throw ──────────
  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real old install (v1.5.0 era) crashed: ${error.message}`);
  }
  console.log('   ✓ an old (pre-migration-array) install migrates through to the latest schema without crashing');

  const db = getDatabase();
  assert.equal(db.prepare("SELECT value FROM settings WHERE key = 'taxes_enabled'").get(), undefined,
    'v81 purges the taxation toggle along with the module');
  // An install old enough to predate the migration array carries cloud settings
  // and outbox tables from every era of the bridge. v80 has to leave none of
  // them behind, whatever route the database took to get here.
  assert.equal(
    (db.prepare(`SELECT COUNT(*) AS count FROM settings
      WHERE key LIKE 'cloud_%' OR key LIKE 'telemetry_%'
         OR key IN ('anonymous_data_consent', 'diagnostics_consent')`).get() as { count: number }).count,
    0,
    'upgrading an old install leaves no cloud or telemetry settings behind');
  assert.equal(
    (db.prepare(`SELECT COUNT(*) AS count FROM sqlite_master
      WHERE type = 'table' AND name IN ('cloud_sync_outbox', 'support_ticket_outbox', 'store_diagnostics_outbox')`).get() as { count: number }).count,
    0,
    'the outbox tables are dropped on upgrade');
  console.log('   ✓ upgrading preserves deliberate settings and removes every trace of the cloud bridge');
  const ideal = buildIdealSchemaDb();
  const latestSchemaVersion = ideal.pragma('user_version', { simple: true }) as number;
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion,
    'migrated old install reaches the same schema version as a fresh install');
  ideal.close();
  assert.equal(
    db.prepare("SELECT value FROM settings WHERE key = 'split_checks_enabled'").get(),
    undefined,
    'upgrading takes the split-check setting away with the feature',
  );
  assert.equal(
    (db.prepare('PRAGMA table_info(bills)').all() as { name: string }[]).filter((column) => column.name.startsWith('split_')).length,
    0,
    'and the split columns are gone from bills',
  );
  console.log('   ✓ upgrading removes split checks, setting and columns');
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'bill_template'").get() as { value: string }).value,
    'classic',
    'existing stores receive the classic bill template during upgrade',
  );
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'bill_footer_message'").get() as { value: string }).value,
    '',
    'existing stores receive an empty bill footer during upgrade',
  );
  console.log('   ✓ existing stores receive bill template defaults without requiring a first save');

  const migratedUpi = db.prepare(`
    SELECT pm.id, pm.name, b.payment_details
    FROM bills b
    JOIN payment_methods pm ON pm.id = json_extract(b.payment_details, '$.payment_method_id')
    WHERE b.bill_number = 'INV-LEGACY-TAX'
  `).get() as { id: number; name: string; payment_details: string };
  assert.equal(migratedUpi.name, 'UPI', 'historical UPI is preserved as a custom method on upgrade');
  assert.equal(JSON.parse(migratedUpi.payment_details).method, 'UPI', 'historical UPI payment is linked to the preserved method');
  console.log('   ✓ legacy UPI payments are preserved without seeding UPI on fresh installs');

  // ── Migration v45: legacy ISO timestamps are normalized to the space form ─
  const isoOrderRow = db.prepare(
    `SELECT created_at, updated_at, cooking_started_at, ready_at FROM orders WHERE order_number = 'ORD-ISO-TS'`
  ).get() as { created_at: string; updated_at: string; cooking_started_at: string; ready_at: string };
  assert.deepEqual(
    [isoOrderRow.created_at, isoOrderRow.updated_at, isoOrderRow.cooking_started_at, isoOrderRow.ready_at],
    ['2026-07-01 10:00:00', '2026-07-01 10:00:00', '2026-07-01 10:05:00', '2026-07-01 10:12:00'],
    'v45 normalizes legacy ISO order timestamps to the space form (second precision)',
  );
  const isoBillRow = db.prepare(
    `SELECT created_at, updated_at, paid_at FROM bills WHERE bill_number = 'INV-ISO-TS'`
  ).get() as { created_at: string; updated_at: string; paid_at: string };
  assert.deepEqual(
    [isoBillRow.created_at, isoBillRow.updated_at, isoBillRow.paid_at],
    ['2026-07-01 11:00:00', '2026-07-01 11:30:00', '2026-07-01 11:30:00'],
    'v45 normalizes legacy ISO bill timestamps to the space form',
  );
  assert.ok(
    db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'index' AND name = 'idx_bills_paid_at'`).get(),
    'v45 creates idx_bills_paid_at for the payment-method breakdown scan',
  );
  console.log('   ✓ legacy ISO timestamps are normalized to the space form (v45)');

  const customerColumns = db.prepare(`PRAGMA table_info(customers)`).all().map((c: any) => c.name);
  assert.ok(customerColumns.includes('country_code'), 'customers.country_code exists after migrating an old install');
  assert.ok(customerColumns.includes('tag_counts'), 'customers.tag_counts exists after migrating an old install');
  console.log('   ✓ customers.country_code and customers.tag_counts are present (the 9c92409 regression)');

  const removedTaxTables = [
    'country_packs',
    'country_pack_versions',
    'tax_categories',
    'tax_rules',
    'tax_overrides',
    'tax_config_audit',
  ];
  for (const table of removedTaxTables) {
    assert.ok(
      !db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?`).get(table),
      `${table} is gone after upgrading an old install`,
    );
  }
  const retainedTaxColumns: Record<string, string[]> = {
    products: ['tax_category_id', 'tax_behavior', 'tax_type', 'tax_rate'],
    addons: ['tax_category_id', 'tax_behavior', 'inherit_parent_tax_category'],
    orders: [
      'tax_snapshot',
      'packaging_tax_category_id',
      'delivery_tax_category_id',
      'service_charge_tax_category_id',
    ],
    order_items: ['tax_snapshot'],
    bills: ['tax_snapshot'],
  };
  for (const [table, expected] of Object.entries(retainedTaxColumns)) {
    const columns = db.prepare(`PRAGMA table_info(${table})`).all().map((column: any) => column.name);
    for (const column of expected) {
      assert.ok(columns.includes(column), `${table}.${column} is kept after upgrading an old install`);
    }
  }
  console.log('   ✓ upgrading drops the taxation tables and keeps the historical amount columns');

  assert.equal((db.prepare('SELECT COUNT(*) AS count FROM products').get() as any).count, 10);
  const preservedOrder = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM orders WHERE order_number = 'ORD-LEGACY-TAX'
  `).get() as any;
  const preservedBill = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM bills WHERE bill_number = 'INV-LEGACY-TAX'
  `).get() as any;
  assert.deepEqual(
    { tax_amount: preservedOrder.tax_amount, tax_breakdown: preservedOrder.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.deepEqual(
    { tax_amount: preservedBill.tax_amount, tax_breakdown: preservedBill.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.equal(preservedOrder.tax_snapshot, null);
  assert.equal(preservedBill.tax_snapshot, null);
  console.log('   ✓ existing products, orders, bills, and legacy tax breakdowns are preserved');

  // ── The migrated old install must match the ideal (fresh) schema exactly ─
  const report = runHealthCheck();
  assert.equal(report.findings.length, 0,
    `a migrated old install should match a fresh install's schema exactly, found: ${JSON.stringify(report.findings)}`);
  console.log('   ✓ runHealthCheck() reports zero drift between the migrated old install and a fresh install');

  // ── The columns must actually be usable, not just present ───────────────
  const customerId = db.prepare(`SELECT id FROM customers LIMIT 1`).get() as { id: string } | undefined;
  if (customerId) {
    db.prepare(`UPDATE customers SET country_code = '+1', tag_counts = '{}' WHERE id = ?`).run(customerId.id);
    const row = db.prepare(`SELECT country_code, tag_counts FROM customers WHERE id = ?`).get(customerId.id) as any;
    assert.equal(row.country_code, '+1');
    assert.equal(row.tag_counts, '{}');
    console.log('   ✓ the backfilled columns are readable and writable');
  }

  db.prepare("INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES ('split_checks_enabled', 'true', datetime('now'))").run();
  db.pragma('user_version = 37');
  closeDatabase();
  initDatabase();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion);
  assert.equal(runHealthCheck().findings.length, 0);
  // A rewound database walks v59/v60 again, so the columns come back and the
  // setting is reinserted; v91 has to sweep up on every pass, not just once.
  assert.equal(
    getDatabase().prepare("SELECT value FROM settings WHERE key = 'split_checks_enabled'").get(),
    undefined,
    'replaying the migrations removes the split-check setting again',
  );
  // Replaying from an older stamp must land in the same place: a rewound
  // database walks the cloud migrations again and v80 has to sweep up after
  // them every time, not only on the first pass.
  getDatabase().prepare(
    `INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES ('diagnostics_consent', 'false', datetime('now'))`,
  ).run();
  getDatabase().pragma('user_version = 46');
  closeDatabase();
  initDatabase();
  assert.equal(
    getDatabase().prepare(`SELECT value FROM settings WHERE key = 'diagnostics_consent'`).get(),
    undefined,
    'replaying the migrations from an older stamp purges the cloud settings again',
  );
  console.log('   ✓ reopening is idempotent and preserves deliberate settings');
  closeDatabase();

  console.log('='.repeat(60));
  console.log('✅ Upgrade-path regression test passed');
}

main();
